/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppProvider: typeof import('./../components/appProvider/index.vue')['default']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    BetterScroll: typeof import('./../components/betterScroll/index.vue')['default']
    ButtonIcon: typeof import('./../components/buttonIcon/index.vue')['default']
    ButtonTab: typeof import('./../components/pageTab/button-tab.vue')['default']
    ChromeTab: typeof import('./../components/pageTab/chrome-tab.vue')['default']
    ChromeTabBg: typeof import('./../components/pageTab/chrome-tab-bg.vue')['default']
    ColorPicker: typeof import('./../components/colorPicker/index.vue')['default']
    DarkModeContainer: typeof import('./../components/darkModeContainer/index.vue')['default']
    Exception: typeof import('./../components/exception/index.vue')['default']
    FullScreenIcon: typeof import('./../components/fullScreenIcon/index.vue')['default']
    PageTab: typeof import('./../components/pageTab/index.vue')['default']
    PickerEnv: typeof import('./../components/pickerEnv/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
